### Data Filtering

In [ ]:
# Primer Ejercicio en pandas

# it has an area of at least three million (i.e., 3000000 km2), or
# it has a population of at least twenty-five million (i.e., 25000000).
import pandas as pd

base = {'name':["Afghanistan","Albania","Algeria","Andorra","Angola"],
        'continent':["Asia","Europe","Africa","Europe","Africa"],
        'area':[652230,28748,2381741,468,1246700],
        'population':[25500100,2831741,37100000,78115,20609294],
        'gdp':[20343000000,12960000000,188681000000,3712000000,100990000000]

}

Base = pd.DataFrame(base)
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    tbl = world[(world["area"] >=  3000000) | (world["population"] >= 25000000)].loc[:,["name","area","population"]]
    return tbl

big_countries(Base)

          name     area  population
0  Afghanistan   652230    25500100
2      Algeria  2381741    37100000

In [ ]:
# Segundo Ejercicio En Pandas 
# Productos en baja ggrasa y reciclable 
base = {
    "product_id": [0, 1, 2, 3, 4],
    "low_fats": ["Y", "Y", "N", "Y", "N"],
    "recyclable": ["N", "Y", "Y", "Y", "N"]
}

products = pd.DataFrame(base)

def find_products(products: pd.DataFrame) -> pd.DataFrame:
    bd = products.loc[(products["low_fats"] == "Y") & (products["recyclable"] == "Y"),"product_id"]
    return pd.DataFrame(bd)

find_products(products)

   product_id
1           1
3           3

In [ ]:
# Tercer Ejercicio de Pandas
# Customers Who Never Order

import pandas as pd

# Tabla Customers
customers_base = {
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"]
}

customers = pd.DataFrame(customers_base)

# Tabla Orders
orders_base = {
    "id": [1, 2],
    "customerId": [3, 1]
}

orders = pd.DataFrame(orders_base)

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    df = pd.merge(customers,orders["customerId"],how = "left",left_on = "id", right_on = "customerId")
    return df.loc[df["customerId"].isnull(),["name"]].rename(columns={"name":"Customers"})

find_customers(customers,orders)

  Customers
1     Henry
3       Max

In [13]:
# Cuarto Ejercicio de pandas 
# Article Views I

# Write a solution to find all the authors that viewed at least one of their own articles.
# Return the result table sorted by id in ascending order.
# The result format is in the following example.

import pandas as pd

views_base = {
    "article_id": [1, 1, 2, 2, 4, 3, 3],
    "author_id":  [3, 3, 7, 7, 7, 4, 4],
    "viewer_id":  [5, 6, 7, 6, 1, 4, 4],
    "view_date": [
        "2019-08-01",
        "2019-08-02",
        "2019-08-01",
        "2019-08-02",
        "2019-07-22",
        "2019-07-21",
        "2019-07-21"
    ]
}

views = pd.DataFrame(views_base)

# Convertir la fecha al tipo datetime (recomendado)
views["view_date"] = pd.to_datetime(views["view_date"])

def article_views(views: pd.DataFrame) -> pd.DataFrame:
    db = views.loc[views["author_id"] == views["viewer_id"],["viewer_id"]]\
        .sort_values(by="viewer_id",ascending=True)\
        .drop_duplicates()\
        .rename(columns={"viewer_id":"id"})
    return db

article_views(views)

   id
5   4
2   7

### String Methods

In [ ]:
# Quinto Ejercicio de pandas 
#Invalid Tweets
# Write a solution to find the IDs of the invalid tweets.
#  The tweet is invalid if the number of characters used in 
# the content of the tweet is strictly greater than 15.
# Return the result table in any order.
# The result format is in the following example.


tweets_base = {
    "tweet_id": [1, 2],
    "content": [
        "Let us Code",
        "More than fifteen chars are here!"
    ]
}


tweets = pd.DataFrame(tweets_base)

def invalid_tweets(tweets: pd.DataFrame) -> pd.DataFrame:
    db = tweets.loc[tweets["content"].str.len() > 15,["tweet_id"]]
    return db

invalid_tweets(tweets)

   tweet_id
1         2

In [29]:
# Sexto ejercicio de panda
# Calculate Special Bonus
# Write a solution to calculate the bonus of each employee.
# The bonus of an employee is 100% of their salary if the ID of the employee is an odd number
#  and the employee's name does not start with the character 'M'.
# The bonus of an employee is 0 otherwise.

# Return the result table ordered by employee_id.

import pandas as pd

employees_base = {
    "employee_id": [2, 3, 7, 8, 9],
    "name": ["Meir", "Michael", "Addilyn", "Juan", "Kannon"],
    "salary": [3000, 3800, 7400, 6100, 7700]
}

employees = pd.DataFrame(employees_base)

def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    employees["bonus"] = 0
    employees.loc[(employees["employee_id"]%2 != 0 ) & (employees["name"]\
                                                        .str[0]!="M"),"bonus"] = employees["salary"]
    return employees[["employee_id","bonus"]].sort_values(by="employee_id",ascending=True)

# Una función alternativa 

def calculate_special_bonus1(employees: pd.DataFrame) -> pd.DataFrame:
    from numpy import where
    employees["bonus"] = where(
        (employees["employee_id"]%2 != 0) &
        (employees["name"].str[0] != "M"),
        employees["salary"],
        0
    )
    return employees[["employee_id","bonus"]]

calculate_special_bonus(employees)

   employee_id  bonus
0            2      0
1            3      0
2            7   7400
3            8      0
4            9   7700

In [53]:
# séptimo ejericio de pandas 
# Fix Names in a Table
# Write a solution to fix the names so that only the first character is uppercase and the rest are lowercase.

# Return the result table ordered by user_id.
import pandas as pd

users_base = {
    "user_id": [1, 2],
    "name": ["aLice", "bOB"]
}

users = pd.DataFrame(users_base)

def fix_names(users: pd.DataFrame) -> pd.DataFrame:
    users["name"] = users["name"].str.capitalize()
    return pd.DataFrame(users)

# Función alternativa 
def fix_names1(users: pd.DataFrame) -> pd.DataFrame:
    users["name"] = list(map(lambda x: x.capitalize(),users["name"]))
    return users

fix_names1(users)

   user_id   name
0        1  Alice
1        2    Bob

In [100]:
# # Octavo ejercicio de pandas 
# # Find Users With Valid E-Mails
# # Write a solution to find the users who have valid emails.

# # A valid e-mail has a prefix name and a domain where:

# The prefix name is a string that may contain letters 
# (upper or lower case), digits, underscore '_', period '.', and/or dash '-'. 
# The prefix name must start with a letter.
# The domain must be exactly '@leetcode.com' in lowercase.

import pandas as pd

users_base = {
    "user_id": [1, 2, 3, 4, 5, 6, 7],
    "name": [
        "Winston",
        "Jonathan",
        "Annabelle",
        "Sally",
        "Marwan",
        "David",
        "Shapiro"
    ],
    "mail": [
        "winston@leetcode.com",
        "jonathanisgreat",
        "bella-@leetcode.com",
        "sally.come@leetcode.com",
        "quarz#2020@leetcode.com",
        "david69@gmail.com",
        ".shapiro@leetcode.com"
    ]
}

users = pd.DataFrame(users_base)

def valid_emails(users: pd.DataFrame) -> pd.DataFrame:
    users["col_separado"] = users["mail"].str.split("@")
    users["dominio"] = [x[-1] for x in users["col_separado"]]
    users["pre_nombre"] = [x[0] for x in users["col_separado"]]
    users = users.loc[(users["dominio"] == "leetcode.com") &  (users["pre_nombre"].str.fullmatch(r"[A-Za-z][A-Za-z0-9_.-]*"))]
    return users[["user_id","name","mail"]]

valid_emails(users)

   user_id       name                     mail
0        1    Winston     winston@leetcode.com
2        3  Annabelle      bella-@leetcode.com
3        4      Sally  sally.come@leetcode.com

In [104]:
# Noveno ejercicico de pandas 

# Patients With a Condition
# Write a solution to find the patient_id, patient_name, 
# and conditions of the patients who have Type I Diabetes.
# Type I Diabetes always starts with DIAB1 prefix.



patients_base = {
    "patient_id": [1, 2, 3, 4, 5],
    "patient_name": ["Daniel", "Alice", "Bob", "George", "Alain"],
    "conditions": [
        "YFEV COUGH",
        "",
        "DIAB100 MYOP",
        "ACNE DIAB100",
        "DIAB201"
    ]
}

patients = pd.DataFrame(patients_base)

def find_patients(patients: pd.DataFrame) -> pd.DataFrame:
    patients = patients.loc[patients["conditions"].str.contains("DIAB1")]
    return patients

find_patients(patients)

   patient_id patient_name    conditions
2           3          Bob  DIAB100 MYOP
3           4       George  ACNE DIAB100

### Data Manipulation

In [ ]:
# # decimo ejercicio de pandas 
# # Nth Highest Salary
# Write a solution to find the nth highest distinct salary from the Employee table. 
# If there are less than n distinct salaries, return null.

import pandas as pd

employee_base = {
    "id": [1, 2, 3, 4],
    "salary": [100, 200, 300,100]
}

employee = pd.DataFrame(employee_base)

def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:

    employee = employee.sort_values(by = "salary",ascending=False)
    employee.drop_duplicates(subset=["salary"] ,inplace=True)
    employee["indicador"] = range(1,employee.shape[0]+1)
    employee = employee[employee["indicador"] == N]

    if len(employee) == 0:
        bd = pd.DataFrame({f"getNthHighestSalary({N})":[None]})
        return bd
    else:
        bd = employee.rename(columns={"salary":f"getNthHighestSalary({N})"})
        return pd.DataFrame(bd.iloc[:, 1])


# nth_highest_salary(employee,2)

   getNthHighestSalary(2)
1                     200

In [ ]:
# décimo primero ejercicio de pandas 

# Second Highest Salary

# Write a solution to find the second highest distinct salary from the Employee table.
# If there is no second highest salary, return null (return None in Pandas).

import pandas as pd

employee_base = {
    "id": [1,2,3],
    "salary": [100,200,300]
}

employee = pd.DataFrame(employee_base)

def second_highest_salary(employee: pd.DataFrame) -> pd.DataFrame:
    try:
        valor = pd.DataFrame(employee["salary"].drop_duplicates().nlargest(2)).iloc[1,:].iloc[0]
        return pd.DataFrame({"SecondHighestSalary":[valor]})
    except IndexError :
        return pd.DataFrame({"SecondHighestSalary": [None]})

second_highest_salary(employee)

   SecondHighestSalary
0                  200

In [ ]:
# Décimo segundo ejercicio
# Department Highest Salary

# Write a solution to find employees who have the highest salary in each of the departments.


import pandas as pd

employee_base = {
    "id": [1, 2, 3, 4, 5],
    "name": ["Joe", "Jim", "Henry", "Sam", "Max"],
    "salary": [70000, 90000, 80000, 60000, 90000],
    "departmentId": [1, 1, 2, 2, 1]
}

employee = pd.DataFrame(employee_base)

# print(employee)

department_base = {
    "id": [1, 2],
    "name": ["IT", "Sales"]
}

department = pd.DataFrame(department_base)

# print(department)

def department_highest_salary(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:
    employee["max_salary"] = employee.groupby(["departmentId"])[["salary"]].transform("max")
    bd = employee.loc[employee["salary"] == employee["max_salary"]].\
        merge(department, how="left",left_on="departmentId",right_on="id")\
            [["name_y","name_x","salary"]].\
                rename(columns={"name_y":"Department",
                            "name_x":"Employee",
                            "salary":"Salary"})
    
    return bd

    
department_highest_salary(employee,department)

   id   name  salary  departmentId
0   1    Joe   70000             1
1   2    Jim   90000             1
2   3  Henry   80000             2
3   4    Sam   60000             2
4   5    Max   90000             1
   id   name
0   1     IT
1   2  Sales

  Department Employee  Salary
0         IT      Jim   90000
1      Sales    Henry   80000
2         IT      Max   90000

In [53]:
# Décimo tercero ejercicio de pandas

# Rank Scores


# Write a solution to find the rank of the scores. 
# The ranking should be calculated according to the following rules:

# The scores should be ranked from the highest to the lowest.
# If there is a tie between two scores, both should have the same ranking.
# After a tie, the next ranking number should be the next consecutive integer value. 
# In other words, there should be no holes between ranks.
# Return the result table ordered by score in descending order.

import pandas as pd

scores_base = {
    "id": [1, 2, 3, 4, 5, 6],
    "score": [3.50, 3.65, 4.00, 3.85, 4.00, 3.65]
}

scores = pd.DataFrame(scores_base)

print(scores)

import pandas as pd

def order_scores(scores: pd.DataFrame) -> pd.DataFrame:
    scores.sort_values(by="score",ascending=False,inplace=True)
    scores["rank"] = scores["score"].rank(method="dense",ascending=False).astype(int)
    return scores[["score","rank"]]

order_scores(scores)

   id  score
0   1   3.50
1   2   3.65
2   3   4.00
3   4   3.85
4   5   4.00
5   6   3.65

   score  rank
4   4.00     1
2   4.00     1
3   3.85     2
1   3.65     3
5   3.65     3
0   3.50     4

In [ ]:
# Décimo cuarto 

# Delete Duplicate Emails
# Write a solution to delete all duplicate emails, keeping only one unique email with the smallest id.
# For SQL users, please note that you are supposed to write a DELETE statement and not a SELECT one.
# For Pandas users, please note that you are supposed to modify Person in place.
# After running your script, the answer shown is the Person table. 
# The driver will first compile and run your piece of code and then show the Person table. 
# The final order of the Person table does not matter.


person_base = {
    "id": [1, 2, 3],
    "email": [
        "john@example.com",
        "bob@example.com",
        "john@example.com"
    ]
}

person = pd.DataFrame(person_base)

def delete_duplicate_emails(person: pd.DataFrame) -> None:
    person.sort_values(by="id",inplace=True)
    person.drop_duplicates(subset="email",inplace=True)


delete_duplicate_emails(person)
person

   id             email
0   1  john@example.com
1   2   bob@example.com
2   3  john@example.com

   id             email
0   1  john@example.com
1   2   bob@example.com

In [ ]:
# Décimo quinto ejercicio

# Rearrange Products Table

# Write a solution to rearrange the Products table so that each row has (product_id, store, price).
# If a product is not available in a store,
# do not include a row with that product_id and store combination in the result table.


import pandas as pd

products_base = {
    "product_id": [0, 1],
    "store1": [95, 70],
    "store2": [100, None],
    "store3": [105, 80]
}

products = pd.DataFrame(products_base)

print(products)

import pandas as pd

def rearrange_products_table(products: pd.DataFrame) -> pd.DataFrame:
    
    product = products.melt(id_vars=["product_id"],var_name="store",value_name="price").\
    dropna().\
    sort_values(by="product_id")

    product["price"] = product["price"].astype("int")

    return product

rearrange_products_table(products)

   product_id  store1  store2  store3
0           0      95   100.0     105
1           1      70     NaN      80

   product_id   store  price
0           0  store1     95
2           0  store2    100
4           0  store3    105
1           1  store1     70
5           1  store3     80

### Statistics

In [32]:
# Décimo sexto ejercicio de pandas 

# Count Salary Categories

# Write a solution to calculate the number of bank accounts for each salary category. 
# The salary categories are:

# "Low Salary": All the salaries strictly less than $20000.
# "Average Salary": All the salaries in the inclusive range [$20000, $50000].
# "High Salary": All the salaries strictly greater than $50000.
# The result table must contain all three categories. If there are no accounts in a category, return 0.


import pandas as pd
import numpy as np

accounts_base = {
    "account_id": [3, 2, 8, 6],
    "income": [108939, 12747, 87709, 91796]
}

accounts = pd.DataFrame(accounts_base)

print(accounts)

import pandas as pd

def count_salary_categories(accounts: pd.DataFrame) -> pd.DataFrame:
    accounts["category"] = np.where(accounts["income"] < 20000 , "Low Salary",
                np.where((accounts["income"] >= 20000) & (accounts["income"] <= 50000),"Average Salary",
                    "High Salary"))

    return accounts["category"].value_counts().reindex(["Low Salary","Average Salary","High Salary"],
                                            fill_value=0).reset_index().\
                                                rename(columns={"count":"accounts_count"})


count_salary_categories(accounts)

   account_id  income
0           3  108939
1           2   12747
2           8   87709
3           6   91796

         category  accounts_count
0      Low Salary               1
1  Average Salary               0
2     High Salary               3

### Data Aggregation

In [44]:
#  Décimo septimo ejercicio de pandas

# Find Total Time Spent by Each Employee
# Write a solution to calculate the total time in minutes spent by each employee on each day at the office.
# Note that within one day, an employee can enter and leave more than once. 
# The time spent in the office for a single entry is out_time - in_time.

import pandas as pd

employees_base = {
    "emp_id": [1, 1, 1, 2, 2],
    "event_day": [
        "2020-11-28",
        "2020-11-28",
        "2020-12-03",
        "2020-11-28",
        "2020-12-09"
    ],
    "in_time": [4, 55, 1, 3, 47],
    "out_time": [32, 200, 42, 33, 74]
}

employees = pd.DataFrame(employees_base)

print(employees)

def total_time(employees: pd.DataFrame) -> pd.DataFrame:

    employees["total_time"] =  employees["out_time"] - employees["in_time"]
    return employees.groupby(["event_day","emp_id"])[["total_time"]].sum().reset_index().\
    rename(columns={"event_day":"day"})

total_time(employees)

   emp_id   event_day  in_time  out_time
0       1  2020-11-28        4        32
1       1  2020-11-28       55       200
2       1  2020-12-03        1        42
3       2  2020-11-28        3        33
4       2  2020-12-09       47        74

          day  emp_id  total_time
0  2020-11-28       1         173
1  2020-11-28       2          30
2  2020-12-03       1          41
3  2020-12-09       2          27

In [12]:
# Décimo octavo ejercicio de pandas

# Game Play Analysis I

# Write a solution to find the first login date for each player.

import pandas as pd

activity_base = {
    "player_id": [1, 1, 2, 3, 3],
    "device_id": [2, 2, 3, 1, 4],
    "event_date": [
        "2016-03-01",
        "2016-05-02",
        "2017-06-25",
        "2016-03-02",
        "2018-07-03"
    ],
    "games_played": [5, 6, 1, 0, 5]
}

activity = pd.DataFrame(activity_base)

print(activity)

import pandas as pd

def game_analysis(activity: pd.DataFrame) -> pd.DataFrame:
    activity["event_date"] = pd.to_datetime(activity["event_date"])
    return activity.groupby("player_id")[["event_date"]].min().reset_index()\
    .rename(columns={"event_date":"first_login"})

game_analysis(activity)

   player_id  device_id  event_date  games_played
0          1          2  2016-03-01             5
1          1          2  2016-05-02             6
2          2          3  2017-06-25             1
3          3          1  2016-03-02             0
4          3          4  2018-07-03             5

   player_id first_login
0          1  2016-03-01
1          2  2017-06-25
2          3  2016-03-02

In [27]:
# Décimo noveno ejercicio de pandas 

# Number of Unique Subjects Taught by Each Teacher

# Write a solution to calculate the number of unique subjects each teacher teaches in the university.

import pandas as pd

teacher_base = {
    "teacher_id": [1, 1, 1, 2, 2, 2, 2],
    "subject_id": [2, 2, 3, 1, 2, 3, 4],
    "dept_id": [3, 4, 3, 1, 1, 1, 1]
}

teacher = pd.DataFrame(teacher_base)

print(teacher)

def count_unique_subjects(teacher: pd.DataFrame) -> pd.DataFrame:

    return teacher.groupby("teacher_id")[["subject_id"]]\
    .value_counts().reset_index()\
        .value_counts(subset=["teacher_id"])\
            .reset_index().rename(columns={"count":"cnt"}).sort_values(by="teacher_id")

# función alternativa 

def count_unique_subjects1(teacher: pd.DataFrame) -> pd.DataFrame:
    return (
        teacher
        .groupby("teacher_id")["subject_id"]
        .nunique()
        .reset_index(name="cnt")
        
    )

count_unique_subjects1(teacher)

   teacher_id  subject_id  dept_id
0           1           2        3
1           1           2        4
2           1           3        3
3           2           1        1
4           2           2        1
5           2           3        1
6           2           4        1

   teacher_id  cnt
0           1    2
1           2    4

In [9]:
# Vigécimo ejercicio de pandas 

# Classes With at Least 5 Students
# Write a solution to find all the classes that have at least five students.

import pandas as pd

courses_base = {
    "student": ["A", "B", "C", "D", "E", "F", "G", "H", "I"],
    "class": [
        "Math",
        "English",
        "Math",
        "Biology",
        "Math",
        "Computer",
        "Math",
        "Math",
        "Math"
    ]
}

courses = pd.DataFrame(courses_base)

print(courses)

import pandas as pd

def find_classes(courses: pd.DataFrame) -> pd.DataFrame:
    bd1 = courses.groupby("class")[["student"]]\
        .size()\
        .reset_index(name="conteo")
    return bd1.loc[bd1["conteo"]>=5,["class"]]

find_classes(courses)

  student     class
0       A      Math
1       B   English
2       C      Math
3       D   Biology
4       E      Math
5       F  Computer
6       G      Math
7       H      Math
8       I      Math

  class
3  Math

In [ ]:
# Vigésimo primer erjercicio de pandas

# Customer Placing the Largest Number of Orders

# Write a solution to find the customer_number for the 
# customer who has placed the largest number of orders.

# The test cases are generated so that exactly one 
# customer will have placed more orders than any other customer.

import pandas as pd

orders_base = {
    "order_number": [3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "customer_number": [5, 1, 5, 4, 6, 2, 4, 16, 3, 5, 3, 16]
}

orders = pd.DataFrame(orders_base)

print(orders)

def largest_orders(orders: pd.DataFrame) -> pd.DataFrame:
    bd1 = orders.groupby("customer_number")[["order_number"]]\
        .size()\
        .reset_index(name="conteo")  
    return bd1.nlargest(1,columns="conteo")[["customer_number"]]
        

largest_orders(orders)

    order_number  customer_number
0              3                5
1              5                1
2              6                5
3              7                4
4              8                6
5              9                2
6             10                4
7             11               16
8             12                3
9             13                5
10            14                3
11            15               16

   customer_number
4                5

In [37]:
# Vigésimo segundo ejercicio de pandas
# Group Sold Products By The Date

# Write a solution to find for each date the number of different products sold and their names.
# The sold products names for each date should be sorted lexicographically.
# Return the result table ordered by sell_date.

import pandas as pd

activities_base = {
    "sell_date": [
        "2020-05-30",
        "2020-06-01",
        "2020-06-02",
        "2020-05-30",
        "2020-06-01",
        "2020-06-02",
        "2020-05-30"
    ],
    "product": [
        "Headphone",
        "Pencil",
        "Mask",
        "Basketball",
        "Bible",
        "Mask",
        "T-Shirt"
    ]
}

activities = pd.DataFrame(activities_base)

print(activities)

def categorize_products(activities: pd.DataFrame) -> pd.DataFrame:
    activities["sell_date"] = pd.to_datetime(activities["sell_date"])
    return activities.groupby("sell_date")\
        .agg(
        num_sold=("product",lambda x:len(x.unique())),
        products = ("product",lambda x: ",".join(sorted(x.unique())))
        ).reset_index()

categorize_products(activities)

    sell_date     product
0  2020-05-30   Headphone
1  2020-06-01      Pencil
2  2020-06-02        Mask
3  2020-05-30  Basketball
4  2020-06-01       Bible
5  2020-06-02        Mask
6  2020-05-30     T-Shirt

   sell_date  num_sold                      products
0 2020-05-30         3  Basketball,Headphone,T-Shirt
1 2020-06-01         2                  Bible,Pencil
2 2020-06-02         1                          Mask

In [12]:
# Vigésimo tercer ejercicio de pandas 
# Daily Leads and Partners

# For each date_id and make_name, find the number of distinct lead_id's and distinct partner_id's.

daily_sales_base = {
    "date_id": [
        "2020-12-8", "2020-12-8", "2020-12-8",
        "2020-12-7", "2020-12-7",
        "2020-12-8",
        "2020-12-8",
        "2020-12-7", "2020-12-7", "2020-12-7"
    ],
    "make_name": [
        "toyota", "toyota", "toyota",
        "toyota", "toyota",
        "honda",
        "honda",
        "honda", "honda", "honda"
    ],
    "lead_id": [0, 1, 1, 0, 0, 1, 2, 0, 1, 2],
    "partner_id": [1, 0, 2, 2, 1, 2, 1, 1, 2, 1]
}

daily_sales = pd.DataFrame(daily_sales_base)

print(daily_sales)

def daily_leads_and_partners(daily_sales: pd.DataFrame) -> pd.DataFrame:
    daily_sales["date_id"] = pd.to_datetime(daily_sales["date_id"])

    return daily_sales.groupby(["date_id","make_name"])[["lead_id","partner_id"]]\
        .nunique()\
        .reset_index()\
        .rename(columns={"lead_id":"unique_leads","partner_id":"unique_partners"})

daily_leads_and_partners(daily_sales)

     date_id make_name  lead_id  partner_id
0  2020-12-8    toyota        0           1
1  2020-12-8    toyota        1           0
2  2020-12-8    toyota        1           2
3  2020-12-7    toyota        0           2
4  2020-12-7    toyota        0           1
5  2020-12-8     honda        1           2
6  2020-12-8     honda        2           1
7  2020-12-7     honda        0           1
8  2020-12-7     honda        1           2
9  2020-12-7     honda        2           1

     date_id make_name  unique_leads  unique_partners
0 2020-12-07     honda             3                2
1 2020-12-07    toyota             1                2
2 2020-12-08     honda             2                2
3 2020-12-08    toyota             2                3

### Data Integration

In [40]:
# Vigésimo cuarto ejercicio de pandas

# Actors and Directors Who Cooperated At Least Three Times

# Write a solution to find all the pairs (actor_id, director_id) where the actor has cooperated
#  with the director at least three times.

import pandas as pd

actor_director = {
    "actor_id": [1, 1, 1, 1, 1, 2, 2],
    "director_id": [1, 1, 1, 2, 2, 1, 1],
    "timestamp": [0, 1, 2, 3, 4, 5, 6]
}


actor_director = pd.DataFrame(actor_director)
print(actor_director)

def actors_and_directors(actor_director: pd.DataFrame) -> pd.DataFrame:
    base = actor_director.groupby(["actor_id","director_id"]).size().reset_index(name="conteo")
    return base.loc[base["conteo"]>=3,["actor_id","director_id"]]

actors_and_directors(actor_director)

   actor_id  director_id  timestamp
0         1            1          0
1         1            1          1
2         1            1          2
3         1            2          3
4         1            2          4
5         2            1          5
6         2            1          6

   actor_id  director_id
0         1            1

In [3]:
# vigésimo quinto ejercico de pandas
#  Replace Employee ID With The Unique Identifier

# Write a solution to show the unique ID of each user,
#  If a user does not have a unique ID replace just show null.

import pandas as pd

Employees = pd.DataFrame({
    "id": [1, 7, 11, 90, 3],
    "name": ["Alice", "Bob", "Meir", "Winston", "Jonathan"]
})

EmployeeUNI = pd.DataFrame({
    "id": [3, 11, 90],
    "unique_id": [1, 2, 3]
})

print(Employees)
print()
print(EmployeeUNI)

def replace_employee_id(employees: pd.DataFrame, employee_uni: pd.DataFrame) -> pd.DataFrame:
    bd = pd.merge(Employees,EmployeeUNI,how="left",left_on="id",right_on="id")\
        [["unique_id","name"]]
    bd["unique_id"] = bd["unique_id"].astype("Int64")
    return bd

replace_employee_id(Employees,EmployeeUNI)

   id      name
0   1     Alice
1   7       Bob
2  11      Meir
3  90   Winston
4   3  Jonathan

   id  unique_id
0   3          1
1  11          2
2  90          3

   unique_id      name
0       <NA>     Alice
1       <NA>       Bob
2          2      Meir
3          3   Winston
4          1  Jonathan

In [32]:
# vigésimo sexto ejercicio de pandas 

# Students and Examinations

# Write a solution to find the number of times each student attended each exam.

# Return the result table ordered by student_id and subject_name.

students_base = {
    "student_id": [1, 2, 13, 6],
    "student_name": [None, "Bob", "John", "Alex"]
}

students = pd.DataFrame(students_base)

print(students)


subjects_base = {
    "subject_name": ["Math", "Physics", "Programming"]
}

subjects = pd.DataFrame(subjects_base)

print(subjects)

examinations_base = {
    "student_id": [1, 1, 1, 2, 1, 1, 13, 13, 13, 2, 1],
    "subject_name": [
        "Math",
        "Physics",
        "Programming",
        "Programming",
        "Physics",
        "Math",
        "Math",
        "Programming",
        "Physics",
        "Math",
        "Math"
    ]
}

examinations = pd.DataFrame(examinations_base)

print(examinations)

import pandas as pd

def students_and_examinations(students: pd.DataFrame, subjects: pd.DataFrame, examinations: pd.DataFrame) -> pd.DataFrame:
    bd = pd.merge(students,subjects,how="cross")
    bd1 = pd.merge(bd,examinations,how="left", left_on="student_id",right_on="student_id")
    bd1
    bd1["attended_exams"] = (
        bd1["subject_name_x"] == bd1["subject_name_y"]
    ).astype(int)

    bd1["attended_exams"] = (
        bd1.groupby(["student_id", "subject_name_x"])["attended_exams"]
        .transform("sum")
    )
    bd2 = (bd1.groupby(["student_id","subject_name_x"])
        ["attended_exams"].max().
        reset_index())
    bd3 = pd.merge(bd2,students,how="left",left_on="student_id",right_on="student_id")
    bd3 = bd3.sort_values(by=["student_id","student_name"],ascending=True)\
        .rename(columns={"subject_name_x":"subject_name"})
    return bd3[["student_id","student_name","subject_name","attended_exams"]]

students_and_examinations(students,subjects,examinations)

   student_id student_name
0           1         None
1           2          Bob
2          13         John
3           6         Alex
  subject_name
0         Math
1      Physics
2  Programming
    student_id subject_name
0            1         Math
1            1      Physics
2            1  Programming
3            2  Programming
4            1      Physics
5            1         Math
6           13         Math
7           13  Programming
8           13      Physics
9            2         Math
10           1         Math

    student_id student_name subject_name  attended_exams
0            1         None         Math               3
1            1         None      Physics               2
2            1         None  Programming               1
3            2          Bob         Math               1
4            2          Bob      Physics               0
5            2          Bob  Programming               1
6            6         Alex         Math               0
7            6         Alex      Physics               0
8            6         Alex  Programming               0
9           13         John         Math               1
10          13         John      Physics               1
11          13         John  Programming               1

In [57]:
# Vigésimo séptimo ejercicio de pandas 

# Managers with at Least 5 Direct Reports

# Write a solution to find managers with at least five direct reports.

import pandas as pd

employee_base = {
    "id": [101, 102, 103, 104, 105, 106],
    "name": ["John", "Dan", "James", "Amy", "Anne", "Ron"],
    "department": ["A", "A", "A", "A", "A", "B"],
    "managerId": [None, 101, 101, 101, 101, 101]
}

employee = pd.DataFrame(employee_base)

print(employee)

def find_managers(employee: pd.DataFrame) -> pd.DataFrame:
    bd = employee["managerId"].value_counts().reset_index()
    l1 = bd.loc[bd["count"]>=5,["managerId"]]
    l1 = l1["managerId"].astype("int").tolist()
    bdr = employee.loc[employee["id"].isin(l1)][["name"]]
    return bdr

find_managers(employee)

    id   name department  managerId
0  101   John          A        NaN
1  102    Dan          A      101.0
2  103  James          A      101.0
3  104    Amy          A      101.0
4  105   Anne          A      101.0
5  106    Ron          B      101.0

   name
0  John

In [90]:
# vigésimo octavo ejercicio de pandas

# Sales Person 

# Write a solution to find the names of all the salespersons who did not have any orders 
# related to the company with the name "RED".

import pandas as pd

# 1. Crear la tabla SalesPerson
salesperson_data = {
    'sales_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Amy', 'Mark', 'Pam', 'Alex'],
    'salary': [100000, 12000, 65000, 25000, 5000],
    'commission_rate': [6, 5, 12, 25, 10],
    'hire_date': ['4/1/2006', '5/1/2010', '12/25/2008', '1/1/2005', '2/3/2007']
}
df_salesperson = pd.DataFrame(salesperson_data)

# 2. Crear la tabla Company
company_data = {
    'com_id': [1, 2, 3, 4],
    'name': ['RED', 'ORANGE', 'YELLOW', 'GREEN'],
    'city': ['Boston', 'New York', 'Boston', 'Austin']
}
df_company = pd.DataFrame(company_data)

# 3. Crear la tabla Orders
orders_data = {
    'order_id': [1, 2, 3, 4],
    'order_date': ['1/1/2014', '2/1/2014', '3/1/2014', '4/1/2014'],
    'com_id': [3, 4, 1, 1],
    'sales_id': [4, 5, 1, 4],
    'amount': [10000, 5000, 50000, 25000]
}
df_orders = pd.DataFrame(orders_data)

# --- Imprimir las tablas para verificar ---
print("Tabla SalesPerson:")
print(df_salesperson)
print("\n" + "="*40 + "\n")

print("Tabla Company:")
print(df_company)
print("\n" + "="*40 + "\n")

print("Tabla Orders:")
print(df_orders)

def sales_person(sales_person: pd.DataFrame, company: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
        bd1 = pd.merge(orders,company, how="left", left_on="com_id",right_on="com_id")
        bd2 = pd.merge(bd1,sales_person, how="left",left_on="sales_id",right_on="sales_id")
        bd3 = bd2.loc[bd2["name_x"] == "RED"]
        l = bd3["name_y"].tolist()

        bd4 = sales_person.loc[~sales_person["name"].isin(l)][["name"]]
        return bd4

sales_person(df_salesperson,df_company,df_orders)

Tabla SalesPerson:
   sales_id  name  salary  commission_rate   hire_date
0         1  John  100000                6    4/1/2006
1         2   Amy   12000                5    5/1/2010
2         3  Mark   65000               12  12/25/2008
3         4   Pam   25000               25    1/1/2005
4         5  Alex    5000               10    2/3/2007

========================================

Tabla Company:
   com_id    name      city
0       1     RED    Boston
1       2  ORANGE  New York
2       3  YELLOW    Boston
3       4   GREEN    Austin

========================================

Tabla Orders:
   order_id order_date  com_id  sales_id  amount
0         1   1/1/2014       3         4   10000
1         2   2/1/2014       4         5    5000
2         3   3/1/2014       1         1   50000
3         4   4/1/2014       1         4   25000

   name
1   Amy
2  Mark
4  Alex

### Ejercicios adicionales, manejo de archivos

In [1]:
# Ejercicios con python - Manejo de archivos
# --------------------------------------------------------------------- #
# Lectura de las bases de datos para el ejercicio

# --------------------------------------------------------------------- #

import pandas as pd

info_tarjetas = pd.read_excel("base_de_datos.xlsx",sheet_name="informacion_tarjetas")
info_cliente = pd.read_excel("base_de_datos.xlsx",sheet_name="informacion_cliente")
transa = pd.read_excel("base_de_datos.xlsx",sheet_name="transaccional")

In [2]:
# Pregunta 1:

# Determine cuantas transacciones fueron realizadas despues del 15 de abril de 2026.
# ---------------------------------------------------------- #

# le damos el formato necesario a la variable de fechas

transa["fecha_compra"] = pd.to_datetime(transa["fecha_compra"],format="%d.%m.%Y")
# Filtramos de la fecha 15 de abril del 2026 en adelante 

num_bef_date = len(transa.loc[transa["fecha_compra"] > "2026-03-15"])
# ------------------------------------------------------------#
print(f"Despues del 15 de abril del 2026 se registraron {num_bef_date} transacciones")

Despues del 15 de abril del 2026 se registraron 59228 transacciones

In [3]:
# Pregunta 2: 

# Identifique lOS clientes que no registraron ninguna transacción durante el mes de junio de 2026.

# ----------------------------------------------------------- #

# Clientes que registraron transacciones en junio 2026

transa["numero_tarjeta"] = transa["numero_tarjeta"].astype("str")
info_cliente["numero_tarjeta"] = info_cliente["numero_tarjeta"].astype("str")

clie_jun = transa\
    .loc[(transa["fecha_compra"].dt.year == 2026) & (transa["fecha_compra"]\
                                                     .dt.month == 6),"numero_tarjeta"].unique().tolist()

# identificamos de la base de clientes que numeros de tarjetas no estan en clie_jun

no_jun = info_cliente.loc[~info_cliente["numero_tarjeta"].isin(clie_jun),"documento"].tolist()
no_jun = [str(x) for x in no_jun]
# ----------------------------------------------------------- #

print(f"Los documentos de clientes que no tuvieron transacciones en Junio fueron {" , ".join(no_jun)}")

Los documentos de clientes que no tuvieron transacciones en Junio fueron 337536959 , 129526360

In [72]:
# Pregunta 3:

# Calcule el costo mensual total que asume el banco por todas las tarjetas 
# clasificadas en la categoría A.

# ------------------------------------------------------------- #
# Tipos de tarjeta categoria A 

tipo_t_A = info_tarjetas.loc[info_tarjetas["categoria_tarjeta"] == "A","tipo_tarjeta"].tolist()

# identificamos todas las tarjetas de este tipo que estan en circulación 

cant_a = info_cliente.loc[info_cliente["tipo_tarjeta"].isin(tipo_t_A)]

# costo total mensual que asume el banco

costo_mensual = cant_a["tipo_tarjeta"].value_counts().reset_index()\
    .merge(info_tarjetas,on="tipo_tarjeta")

costo_mensual["total"] = costo_mensual["count"]*costo_mensual["costo_mensual_unidad"]

# -------------------------------------------------------------- #
print(f"el total de tarjetas de categoria A que estan en circulación es: {sum(costo_mensual["count"])}")
print(f"El costo total que asume el banco es de: {sum(costo_mensual["total"])}")

el total de tarjetas de categoria A que estan en circulación es: 102
El costo total que asume el banco es de: 4080000

In [59]:
# Pregunta 4:

# El banco obtiene ingresos equivalentes al 1% del valor de cada transacción.

# La rentabilidad deberá calcularse corno:
# Rentabilidad = Ingresos por comisión - Costos mensuales
# Ingresos por comisión sumatoria del valor_compra 1%
# Costos mensuales cantidad de tarjetas en circulación x costo_mensual_unidad

# Objetivo: Determinar cuáles fueron el top 3 de tipos de tarjeta más rentable durante los meses de
# abril y mayo de 2026.

# -------------------------------------------------------------------------------# 
tar_ab_ma = transa\
    .loc[(transa["fecha_compra"].dt.year==2026) &\
          (transa["fecha_compra"].dt.month == 4) | (transa["fecha_compra"].dt.month == 5)]

tar_ab_ma["comisión"] = [x/100 for x in tar_ab_ma["valor_compra"]]

# agregamos el tipo de tarjeta agrupamos y unimos para obtener el costo por unidad 
tar_ab_ma_t = tar_ab_ma\
    .merge(info_cliente[["numero_tarjeta","tipo_tarjeta"]], on="numero_tarjeta")\
    .groupby("tipo_tarjeta")["comisión"].agg(["sum","count"]).reset_index()

cos = tar_ab_ma_t\
    .merge(info_tarjetas[["tipo_tarjeta","costo_mensual_unidad"]],on="tipo_tarjeta")

# Calculamos las columnas necesarias e imprimimos los tres productos mas importantes 
cos["valor_t_t"] = cos["sum"]*100
cos["costo_total"] = cos["count"]*cos["costo_mensual_unidad"]
cos["rentabilida"] = cos["sum"]-cos["costo_total"]
cos.sort_values(by="rentabilida",ascending=False).head(3)

C:\Users\Juan Carvajal\AppData\Local\Temp\ipykernel_22264\427212376.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tar_ab_ma["comisión"] = [x/100 for x in tar_ab_ma["valor_compra"]]

,tipo_tarjeta,sum,count,costo_mensual_unidad,valor_t_t,costo_total,rentabilida
4,AMERICAN EXPRESS PLATINUM,185826465.0,1246,40000,1.858265e+10,49840000,135986465.0
5,MASTERCARD BLACK,180595269.0,1230,40000,1.805953e+10,49200000,131395269.0
10,VISA INFINITE,168320259.0,1117,40000,1.683203e+10,44680000,123640259.0